[build]
target = "riscv64gc-unknown-none-elf"
# target = 'aarch64-unknown-none-softfloat'
# target = 'x86_64-unknown-none'
# target = 'loongarch64-unknown-none'

# [target.'cfg(target_os = "none")']
# runner = "./test.sh"
# rustflags = [
#     "-Clink-arg=-Texample/linker/linker-riscv64.ld",
#     "-Cforce-frame-pointers=yes",
#     '--cfg=board="qemu"',
# ]

[target.riscv64gc-unknown-none-elf]
rustflags = ["-Cforce-frame-pointers=yes"]


# [source.crates-io]
# replace-with = "vendored-sources"

# [source."git+https://github.com/EchudeT/lwext4_rust.git?rev=91ee"]
# git = "https://github.com/EchudeT/lwext4_rust.git"
# rev = "91ee"
# replace-with = "vendored-sources"

# [source."git+https://github.com/EchudeT/rust-fatfs.git?rev=e656"]
# git = "https://github.com/EchudeT/rust-fatfs.git"
# rev = "e656"
# replace-with = "vendored-sources"

# [source."git+https://github.com/adong660/rust-elf.git?branch=no-std-elfstream"]
# git = "https://github.com/adong660/rust-elf.git"
# branch = "no-std-elfstream"
# replace-with = "vendored-sources"

# [source.vendored-sources]
# directory = "vendor"
