[build]
target = 'riscv64gc-unknown-none-elf'

[target.riscv64gc-unknown-none-elf]
rustflags = ["-Cforce-frame-pointers=yes"]

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
