[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/EchudeT/lwext4_rust.git?rev=c115"]
git = "https://github.com/EchudeT/lwext4_rust.git"
rev = "c115"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
