[package]
name = "user_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { workspace = true }
buddy_system_allocator = { workspace = true }
config = { path = "../lib/config/" }
strum = { workspace = true }
