use crate::fork;

#[allow(non_snake_case)]
pub mod ltprun {
    extern crate alloc;
    use crate::run_cmd;
    use alloc::{format, vec::Vec};

    pub fn autorun() {
        let TESTCASES = Vec::from([
            "pidfd_send_signal01",
            "pidfd_send_signal02",
            "pidfd_send_signal03",
            "rt_sigprocmask01",
            "rt_sigprocmask02",
            "rt_sigqueueinfo01",
            "rt_sigsuspend01",
            "sigaction01",
            "sigaction02",
            "sigaltstack01",
            "sigprocmask01",
            "sigrelse01",
            "sigsuspend01",
            "sigtimedwait01",
            "sigwait01",
            "sigwaitinfo01",
        ]);

        println!("#### OS COMP TEST GROUP START ltp-musl ####");
        for test in TESTCASES {
            println!("RUN LTP CASE {}", test);
            let cmd = format!("ltp/testcases/bin/{}", test);
            let _ = run_cmd(&cmd);
            println!("FAIL LTP CASE {} : 0", test);
        }
        println!("#### OS COMP TEST GROUP END ltp-musl ####");
    }

    pub fn runltp_rvml() {
        let RVTESTCASES = Vec::from([
            "fanotify01",
            "splice07",
            "fanotify14",
            "epoll_ctl03",
            "access01",
            "rt_sigaction01",
            "rt_sigaction02",
            "rt_sigaction03",
            "chdir01",
            "waitpid01",
            "fsetxattr01",
            "setxattr01",
            "rename01",
            "rename03",
            "pipe11",
            "mkdir09",
            "memfd_create01",
            "fgetxattr01",
            "clock_getres01",
            "sysconf01",
            "copy_file_range01",
            "chmod01",
            "confstr01",
            "epoll-ltp",
            "posix_fadvise03",
            "posix_fadvise03_64",
            "splice08",
            "signal03",
            "signal05",
            "signal04",
            "fremovexattr02",
            "rename13",
            "utime01",
            "utime02",
            "utime04",
            "accept03",
            "madvise01",
            "fanotify06",
            "llseek03",
            "open_tree02",
            "rename08",
            "rename10",
            "statvfs01",
            "pathconf01",
            "access02",
            "clock_gettime01",
            "fanotify09",
            "clock_nanosleep01",
            "clock_settime02",
            "diotest4",
            "link04",
            "madvise10",
            "utimensat01",
            "clock_gettime02",
            "close_range02",
            "fanotify16",
            "times03",
            "add_key02",
            "arping01.sh",
            "clock_adjtime01",
            "fanotify04",
            // "fpathconf01", //panic
            "fremovexattr01",
            "fspick02",
            "mkdir03",
            "readv01",
            "rename04",
            "rename05",
            "rename06",
            "rename07",
            "statfs01",
            "statfs01_64",
            "access03",
            "access04",
            "add_key01",
            "epoll_ctl02",
            // "fallocate03",
            "fanotify02",
            "fanotify19",
            "fsconfig02",
            "linkat01",
            "bind01",
            "creat06",
            "fcntl36",
            "fcntl36_64",
            "mknod01",
            "setreuid01",
            "splice03",
            "statx01",
            "unlinkat01",
            "utime03",
            "alarm02",
            "capget01",
            "chown05",
            "clock_gettime04",
            "clone302",
            "dup202",
            "fchmodat01",
            "fcntl02",
            "fcntl02_64",
            "fcntl16",
            "fcntl16_64",
            "fstatat01",
            "lchown01",
            "pipe2_01",
            "posix_fadvise01",
            "posix_fadvise01_64",
            "posix_fadvise02",
            "posix_fadvise02_64",
            "tgkill03",
            "waitid05",
            "waitid06",
            "accept01",
            "chmod06",
            "clone08",
            "epoll_wait03",
            "fchmodat02",
            "fcntl05",
            "fcntl05_64",
            "fcntl15_64",
            // "fsconfig03", //too much output
            "open07",
            "openat01",
            "read02",
            "readlinkat02",
            "renameat01",
            "rmdir02",
            "setitimer01",
            "socket01",
            "statx02",
            "statx03",
            "stream05",
            "symlink01",
            "symlinkat01",
            "unlink07",
            "waitid01",
            "waitid11",
            "accept4_01",
            "capget02",
            "chown04",
            "chroot03",
            "clock_nanosleep04",
            "clock_settime01",
            "clone301",
            "creat01",
            "dup203",
            "dup204",
            // "fallocate01",
            // "fallocate06",
            "fchownat01",
            "fcntl09",
            "fcntl09_64",
            "fcntl10",
            "fcntl10_64",
            "fstat02",
            "fstat02_64",
            "ioctl_ns07",
            "linkat02",
            "lseek01",
            "mknod07",
            "mlock01",
            "mmstress",
            "munlock01",
            "pwrite02",
            "pwrite02_64",
            "sched_getaffinity01",
            "sched_setscheduler04",
            "shmt03",
            "sigaction01",
            "signal01",
            "sigpending02",
            "socket02",
            "timerfd02",
            "waitpid04",
            "waitpid09",
            "writev01",
            "alarm05",
            "atof01",
            "capset01",
            "chdir04",
            "clock_adjtime02",
            "close01",
            // "diotest2",
            // "diotest3",
            // "diotest5",
            // "diotest6",
            // "dup07",
            // "epoll_ctl01",
            // // "faccessat01",
            // "fanotify15",
            // "fork04",
            // "getgroups01",
            // "inode01",
            // "ioctl05",
            // "listen01",
            // "mknodat01",
            // "mmap09",
            // "mremap06",
            // "nanosleep04",
            // "nextafter01",
            // // "pidfd_getfd02", // stuck for a while but KILLed in RvGl
            // "prctl02",
            // "readv02",
            // "sendfile03",
            // "sendfile03_64",
            // "setgroups02",
            // "setresuid04",
            // "setreuid04",
            // "setreuid06",
            // "setreuid07",
            // "shmt02",
            // "sigaction02",
            // "signal02",
            // "socketpair01",
            // "statfs02",
            // "statfs02_64",
            // "syscall01",
            // "ulimit01",
            // "wait401",
            // // "waitid07", // stuck for a while but KILLed
            // // "waitid08", // stuck for a while but KILLed
            // "write05",
            // "abort01",
            // "abs01",
            // "adjtimex01",
            // "alarm03",
            // "alarm06",
            // "alarm07",
            // "bind03",
            // "chown02",
            // "clone01",
            // "connect01",
            // "creat04",
            // "dup01",
            // "dup02",
            // "dup04",
            // "dup207",
            // "dup3_01",
            // "dup3_02",
            // "epoll_create01",
            // "epoll_create1_01",
            // "epoll_create1_02",
            // "epoll_wait06",
            // "epoll_wait07",
            // "eventfd01",
            // "eventfd03",
            // "eventfd05",
            // "eventfd2_01",
            // "eventfd2_03",
            // // "faccessat02",
            // "fanotify08",
            // "fcntl23",
            // "fcntl29",
            // "fcntl29_64",
            // "fork01",
            // "fork10",
            // "fsopen02",
            // "fstat03",
            // "fstat03_64",
            // // "ftest01",
            // // "ftest06",
            // "kill03",
            // "kill11",
            // "link02",
            // "llseek02",
            // "lseek07",
            // "memcmp01",
            // "memcpy01",
            // "mknod02",
            // "mknodat02",
            // "mmap06",
            // "nanosleep02",
            // "pidfd_open02",
            // "pidns05",
            // "pipe04",
            // "poll01",
            // "prctl01",
            // "prctl05",
            // "pread02",
            // "pread02_64",
            // "readlink01",
            // "recv01",
            // "recvfrom01",
            // "removexattr02",
            // "sched_getscheduler01",
            // "send01",
            // "sendto01",
            // "setgid03",
            // "setgroups03",
            // "setpgid01",
            // "setpgrp02",
            // "setrlimit01",
            // "setsockopt01",
            // "settimeofday02",
            // "setuid04",
            // "shmctl02",
            // "shmt05",
            // "shmt07",
            // "sigaltstack02",
            // "signalfd01",
            // "socketpair02",
            // "splice09",
            // "stat02",
            // "stat02_64",
            // "statvfs02",
            // "stream03",
            // "symlink04",
            // "time01",
            // "timerfd_create01",
            // "tkill01",
            // "tkill02",
            // "truncate02",
            // "truncate02_64",
            // "umount2_02",
            // "uname01",
            // "unlink05",
            // "unlink08",
            // "utsname04",
            // "waitid04",
            // "waitpid03",
            // "write02",
            // "write06",
            // "writetest",
            // "writev07",
            // "add_key03",
            // "add_key04",
            // "adjtimex02",
            // "bpf_map01",
            // "bpf_prog01",
            // "bpf_prog02",
            // "bpf_prog05",
            // "brk02",
            // "capset03",
            // "chown01",
            // "chroot02",
            // "clock_nanosleep02",
            // "clone03",
            // "clone05",
            // "clone06",
            // "clone07",
            // "close02",
            // "close_range01",
            // // "crash01", // timeout and can't kill in La
            // "creat03",
            // "creat05",
            // "cve-2017-17052",
            // "dio_read",
            // "dio_sparse",
            // "diotest1",
            // "dirtyc0w",
            // "dirtypipe",
            // "dup03",
            // "dup06",
            // "dup205",
            // "dup206",
            // "epoll_wait02",
            // "epoll_wait04",
            // "eventfd02",
            // "eventfd2_02",
            // "execve03",
            // "exit01",
            // "exit02",
            // "exit_group01",
            // "fallocate04",
            // "fchdir01",
            // "fchdir02",
            // "fchownat02",
            // "fcntl03",
            // "fcntl03_64",
            // "fcntl04",
            // "fcntl04_64",
            // "fcntl08",
            // "fcntl08_64",
            // "fcntl12",
            // "fcntl12_64",
            // "fcntl34",
            // "fcntl34_64",
            // "fgetxattr03",
            // "fork03",
            // "fork07",
            // "fork08",
            // "fork09",
            // "fork_procs",
            // "ftest02",
            // "ftest03",
            // "ftest04",
            // "ftest05",
            // "ftest07",
            // "ftest08",
            // "get_robust_list01",
            // "getrusage04",
            // "growfiles",
            // "inode02",
            // "kill06",
            // "kill08",
            // "kill09",
            // "kill12",
            // "lchown03",
            // "lftest",
            // "link05",
            // "link08",
            // "llseek01",
            // "madvise05",
            // "mallocstress",
            // "memfd_create02",
            // "memset01",
            // "mkdir05",
            // "mknod09",
            // "mlock03",
            // "mlock04",
            // "mmap01",
            // "mmap05",
            // "mmap08",
            // // "mmap1", //normally time consuming
            // "mmap11",
            // "mmap18",
            // "mmap19",
            // "mmapstress01",
            // "mmapstress04",
            // "mprotect03",
            // "mprotect04",
            // "mprotect05",
            // "msync01",
            // "msync02",
            // "munmap01",
            // "munmap02",
            // "nanosleep01",
            // "newuname01",
            // "nfs05_make_tree",
            // "nptl01",
            // "open01",
            // "open02",
            // "open03",
            // "open04",
            // "open09",
            // "openat02",
            // "page01",
            // "pathconf02",
            // "pidns32",
            // "pipe01",
            // "pipe05",
            // "pipe06",
            // "pipe07",
            // "pipe09",
            // "pipe10",
            // "pipe12",
            // "pipe14",
            // "pread01",
            // "pread01_64",
            // "pselect01",
            // "pselect01_64",
            // "pselect03",
            // "pselect03_64",
            // "pth_str01",
            // "pth_str02",
            // "pth_str03",
            // "pwrite01",
            // "pwrite01_64",
            // "pwrite03",
            // "pwrite03_64",
            // "pwrite04",
            // "pwrite04_64",
            // "read01",
            // "read04",
            // "readdir01",
            // "removexattr01",
            // "rename14",
            // "renameat201",
            // "rmdir01",
            // "rt_sigprocmask01",
            // "sbrk01",
            // "sbrk02",
            // "sched_setaffinity01",
            // "sched_yield01",
            // "select02",
            // "sendfile06",
            // "sendfile06_64",
            // "sendfile08",
            // "sendfile08_64",
            // "sendto02",
            // "set_robust_list01",
            // "set_tid_address01",
            // "setegid02",
            // "setgid01",
            // "setgid02",
            // "setgroups01",
            // "setgroups04",
            // "setitimer02",
            // "setpgrp01",
            // "setresuid05",
            // "setrlimit02",
            // "setrlimit04",
            // "setrlimit05",
            // "setsid01",
            // "setsockopt03",
            // "setsockopt04",
            // "settimeofday01",
            // "setuid01",
            // "setuid03",
            // "shmctl06",
            // "shmem_2nstest",
            // "shmnstest",
            // "sigaltstack01",
            // "sigprocmask01",
            // "splice01",
            // "splice02",
            // "stack_space",
            // "stime01",
            // "stream01",
            // "stream04",
            // "string01",
            // "symlink02",
            // "sysinfo01",
            // "sysinfo02",
            // "tgkill01",
            // "times01",
            // "umount01",
            // "uname02",
            // "uname04",
            // "utime07",
            // "utsname01",
            // "wait01",
            // "wait02",
            // "wait402",
            // "wait403",
            // "waitid02",
            // "waitid03",
            // "waitid09",
            // "waitid10",
            // "waitpid06",
            // "waitpid07",
            // "waitpid08",
            // "write01",
            // "write03",
            // "writev02",
            // "writev05",
            // "writev06",
        ]);

        println!("#### OS COMP TEST GROUP START ltp-musl ####");
        for test in RVTESTCASES {
            println!("RUN LTP CASE {}", test);
            let cmd = format!("ltp/testcases/bin/{}", test);
            let _ = run_cmd(&cmd);
        }
        println!("#### OS COMP TEST GROUP END ltp-musl ####");
    }

    pub fn runltp_rvgl() {
        let RVTESTCASES = Vec::from([
            "fanotify01",
            "splice07",
            "fanotify14",
            "epoll_ctl03",
            "access01",
            "rt_sigaction01",
            "rt_sigaction02",
            "rt_sigaction03",
            "chdir01",
            "waitpid01",
            "fsetxattr01",
            "setxattr01",
            "rename01",
            "rename03",
            "pipe11",
            "mkdir09",
            // "memfd_create01", // stuck for a while but KILLed
            "fgetxattr01",
            "clock_getres01",
            "sysconf01",
            "copy_file_range01",
            "chmod01",
            "confstr01",
            "epoll-ltp",
            "posix_fadvise03",
            "posix_fadvise03_64",
            "splice08",
            "signal03",
            "signal05",
            "signal04",
            "fremovexattr02",
            "rename13",
            "utime01",
            "utime02",
            "utime04",
            "accept03",
            "madvise01",
            "fanotify06",
            "llseek03",
            "open_tree02",
            "rename08",
            "rename10",
            "statvfs01",
            "pathconf01",
            "access02",
            "clock_gettime01",
            "fanotify09",
            "clock_nanosleep01",
            "clock_settime02",
            "diotest4",
            "link04",
            "madvise10",
            "utimensat01",
            "clock_gettime02",
            "close_range02",
            "fanotify16",
            "times03",
            "add_key02",
            "arping01.sh",
            "clock_adjtime01",
            "fanotify04",
            // "fpathconf01", //panic
            "fremovexattr01",
            "fspick02",
            "mkdir03",
            "readv01",
            "rename04",
            "rename05",
            "rename06",
            "rename07",
            "statfs01",
            "statfs01_64",
            "access03",
            "access04",
            "add_key01",
            "epoll_ctl02",
            // "fallocate03",
            "fanotify02",
            "fanotify19",
            "fsconfig02",
            "linkat01",
            "bind01",
            "creat06",
            "fcntl36",
            "fcntl36_64",
            "mknod01",
            "setreuid01",
            "splice03",
            "statx01",
            // "unlinkat01",
            "utime03",
            "alarm02",
            "capget01",
            "chown05",
            "clock_gettime04",
            // "clone302", // stuck for a while but KILLed
            "dup202",
            "fchmodat01",
            "fcntl02",
            "fcntl02_64",
            "fcntl16",
            "fcntl16_64",
            "fstatat01",
            "lchown01",
            "pipe2_01",
            "posix_fadvise01",
            "posix_fadvise01_64",
            "posix_fadvise02",
            "posix_fadvise02_64",
            // "tgkill03", // stuck for a while but KILLed
            "waitid05",
            "waitid06",
            "accept01",
            "chmod06",
            "clone08",
            "epoll_wait03",
            "fchmodat02",
            "fcntl05",
            "fcntl05_64",
            // "fsconfig03", // too much output
            "open07",
            "openat01",
            "read02",
            "readlinkat02",
            "renameat01",
            "rmdir02",
            // "setitimer01", // stuck for a while but KILLed
            "socket01",
            "statx02",
            "statx03",
            "stream05",
            "symlink01",
            "symlinkat01",
            "unlink07",
            "waitid01",
            "waitid11",
            "accept4_01",
            "capget02",
            "chown04",
            "chroot03",
            "clock_nanosleep04",
            "clock_settime01",
            "clone301",
            "creat01",
            "dup203",
            "dup204",
            // "fallocate01", // no summary output
            // "fallocate06", //too much space
            "fchownat01",
            "fcntl09",
            "fcntl09_64",
            "fcntl10",
            "fcntl10_64",
            "fstat02",
            "fstat02_64",
            "ioctl_ns07",
            "linkat02",
            "lseek01",
            "mknod07",
            "mlock01",
            // "mmstress", // stress
            "munlock01",
            "pwrite02",
            "pwrite02_64",
            "sched_getaffinity01",
            "sched_setscheduler04",
            "shmt03",
            "sigaction01",
            // "signal01", // stuck for a while but KILLed
            "sigpending02",
            "socket02",
            "timerfd02",
            "waitpid04",
            "waitpid09",
            "writev01",
            "alarm05",
            "atof01",
            "capset01",
            "chdir04",
            "clock_adjtime02",
            "close01",
            // "diotest2",
            // "diotest3",
            // "diotest5",
            // "diotest6",
            // "dup07",
            // "epoll_ctl01",
            // // "faccessat01",
            // "fanotify15",
            // "fork04",
            // "getgroups01",
            // "inode01",
            // "ioctl05",
            // "listen01",
            // "mknodat01",
            // "mmap09",
            // "mremap06",
            // "nanosleep04",
            // "nextafter01",
            // // "pidfd_getfd02", // stuck for a while but KILLed in RvGl
            // "prctl02",
            // "readv02",
            // "sendfile03",
            // "sendfile03_64",
            // "setgroups02",
            // "setresuid04",
            // "setreuid04",
            // "setreuid06",
            // "setreuid07",
            // "shmt02",
            // "sigaction02",
            // "signal02",
            // "socketpair01",
            // "statfs02",
            // "statfs02_64",
            // "syscall01",
            // "ulimit01",
            // "wait401",
            // // "waitid07", // stuck for a while but KILLed
            // // "waitid08", // stuck for a while but KILLed
            // "write05",
            // "abort01",
            // "abs01",
            // "adjtimex01",
            // "alarm03",
            // "alarm06",
            // "alarm07",
            // "bind03",
            // "chown02",
            // "clone01",
            // "connect01",
            // "creat04",
            // "dup01",
            // "dup02",
            // "dup04",
            // "dup207",
            // "dup3_01",
            // "dup3_02",
            // "epoll_create01",
            // "epoll_create1_01",
            // "epoll_create1_02",
            // "epoll_wait06",
            // "epoll_wait07",
            // "eventfd01",
            // "eventfd03",
            // "eventfd05",
            // "eventfd2_01",
            // "eventfd2_03",
            // // "faccessat02",
            // "fanotify08",
            // "fcntl23",
            // "fcntl29",
            // "fcntl29_64",
            // "fork01",
            // "fork10",
            // "fsopen02",
            // "fstat03",
            // "fstat03_64",
            // // "ftest01",
            // // "ftest06",
            // "kill03",
            // "kill11",
            // "link02",
            // "llseek02",
            // "lseek07",
            // "memcmp01",
            // "memcpy01",
            // "mknod02",
            // "mknodat02",
            // "mmap06",
            // "nanosleep02",
            // "pidfd_open02",
            // "pidns05",
            // "pipe04",
            // "poll01",
            // "prctl01",
            // "prctl05",
            // "pread02",
            // "pread02_64",
            // "readlink01",
            // "recv01",
            // "recvfrom01",
            // "removexattr02",
            // "sched_getscheduler01",
            // "send01",
            // "sendto01",
            // "setgid03",
            // "setgroups03",
            // "setpgid01",
            // "setpgrp02",
            // "setrlimit01",
            // "setsockopt01",
            // "settimeofday02",
            // "setuid04",
            // "shmctl02",
            // "shmt05",
            // "shmt07",
            // "sigaltstack02",
            // "signalfd01",
            // "socketpair02",
            // "splice09",
            // "stat02",
            // "stat02_64",
            // "statvfs02",
            // "stream03",
            // "symlink04",
            // "time01",
            // "timerfd_create01",
            // "tkill01",
            // "tkill02",
            // "truncate02",
            // "truncate02_64",
            // "umount2_02",
            // "uname01",
            // "unlink05",
            // "unlink08",
            // "utsname04",
            // "waitid04",
            // "waitpid03",
            // "write02",
            // "write06",
            // "writetest",
            // "writev07",
            // "add_key03",
            // "add_key04",
            // "adjtimex02",
            // "bpf_map01",
            // "bpf_prog01",
            // "bpf_prog02",
            // "bpf_prog05",
            // "brk02",
            // "capset03",
            // "chown01",
            // "chroot02",
            // "clock_nanosleep02",
            // "clone03",
            // "clone05",
            // "clone06",
            // "clone07",
            // "close02",
            // "close_range01",
            // "crash01",
            // "creat03",
            // "creat05",
            // "cve-2017-17052",
            // "dio_read",
            // "dio_sparse",
            // "diotest1",
            // "dirtyc0w",
            // "dirtypipe",
            // "dup03",
            // "dup06",
            // "dup205",
            // "dup206",
            // "epoll_wait02",
            // "epoll_wait04",
            // "eventfd02",
            // "eventfd2_02",
            // "execve03",
            // "exit01",
            // "exit02",
            // "exit_group01",
            // "fallocate04",
            // "fchdir01",
            // "fchdir02",
            // "fchownat02",
            // "fcntl03",
            // "fcntl03_64",
            // "fcntl04",
            // "fcntl04_64",
            // "fcntl08",
            // "fcntl08_64",
            // "fcntl12",
            // "fcntl12_64",
            // "fcntl34",
            // "fcntl34_64",
            // "fgetxattr03",
            // "fork03",
            // "fork07",
            // "fork08",
            // "fork09",
            // "fork_procs",
            // "ftest02",
            // "ftest03",
            // "ftest04",
            // "ftest05",
            // "ftest07",
            // "ftest08",
            // "get_robust_list01",
            // "getrusage04",
            // "growfiles",
            // "inode02",
            // "kill06",
            // "kill08",
            // "kill09",
            // "kill12",
            // "lchown03",
            // "lftest",
            // "link05",
            // "link08",
            // "llseek01",
            // "madvise05",
            // "memfd_create02",
            // "memset01",
            // "mkdir05",
            // "mknod09",
            // "mlock03",
            // "mlock04",
            // "mmap01",
            // "mmap05",
            // "mmap08",
            // "mmap1",
            // "mmap11",
            // "mmap18",
            // "mmap19",
            // "mmapstress01",
            // "mmapstress04",
            // "mprotect01",
            // "mprotect03",
            // "mprotect04",
            // "mprotect05",
            // "msync01",
            // "msync02",
            // "munmap01",
            // "munmap02",
            // "nanosleep01",
            // "newuname01",
            // "nfs05_make_tree",
            // "nptl01",
            // "open01",
            // "open02",
            // "open03",
            // "open04",
            // "open09",
            // "openat02",
            // "page01",
            // "page02",
            // "pathconf02",
            // "pidns32",
            // "pipe01",
            // "pipe05",
            // "pipe06",
            // "pipe07",
            // "pipe09",
            // "pipe10",
            // "pipe12",
            // "pipe14",
            // "pread01",
            // "pread01_64",
            // "pselect01",
            // "pselect01_64",
            // "pselect03",
            // "pselect03_64",
            // "pth_str01",
            // "pth_str02",
            // "pth_str03",
            // "pwrite01",
            // "pwrite01_64",
            // "pwrite03",
            // "pwrite03_64",
            // "pwrite04",
            // "pwrite04_64",
            // "read01",
            // "read04",
            // "readdir01",
            // "removexattr01",
            // "rename14",
            // "renameat201",
            // "rmdir01",
            // "rt_sigprocmask01",
            // "sbrk01",
            // "sbrk02",
            // "sched_setaffinity01",
            // "sched_yield01",
            // "select02",
            // "sendfile06",
            // "sendfile06_64",
            // "sendfile08",
            // "sendfile08_64",
            // "sendto02",
            // "set_robust_list01",
            // "set_tid_address01",
            // "setegid02",
            // "setgid01",
            // "setgid02",
            // "setgroups01",
            // "setgroups04",
            // "setitimer02",
            // "setpgrp01",
            // "setresuid05",
            // "setrlimit02",
            // "setrlimit04",
            // "setrlimit05",
            // "setsid01",
            // "setsockopt03",
            // "setsockopt04",
            // "settimeofday01",
            // "setuid01",
            // "setuid03",
            // "shmctl06",
            // // "shmem_2nstest", //Stuck for a while, killed
            // "shmnstest",
            // "sigaltstack01",
            // "sigprocmask01",
            // "splice01",
            // "splice02",
            // "stack_space",
            // "stime01",
            // "stream01",
            // "stream04",
            // "string01",
            // "symlink02",
            // "sysinfo01",
            // "sysinfo02",
            // "tgkill01",
            // "times01",
            // "umount01",
            // "uname02",
            // "uname04",
            // "utime07",
            // "utsname01",
            // "wait01",
            // "wait02",
            // "wait402",
            // "wait403",
            // "waitid02",
            // "waitid03",
            // "waitid09",
            // "waitid10",
            // "waitpid06",
            // "waitpid07",
            // "waitpid08",
            // "write01",
            // "write03",
            // "writev02",
            // "writev05",
            // "writev06",
        ]);

        println!("#### OS COMP TEST GROUP START ltp-glibc ####");
        for test in RVTESTCASES {
            println!("RUN LTP CASE {}", test);
            let cmd = format!("ltp/testcases/bin/{}", test);
            run_cmd(&cmd);
            println!("FAIL LTP CASE {} : 0", test);
        }
        println!("#### OS COMP TEST GROUP END ltp-glibc ####");
    }

    pub fn runltp_laml() {
        let LATESTCASES = Vec::from([
            "fanotify01",
            "splice07",
            "fanotify14",
            "epoll_ctl03",
            "access01",
            "rt_sigaction01",
            "rt_sigaction02",
            "rt_sigaction03",
            "chdir01",
            "waitpid01",
            "fsetxattr01",
            "setxattr01",
            "rename01",
            "rename03",
            "pipe11",
            "mkdir09",
            "memfd_create01", // stuck for a while but KILLed
            "fgetxattr01",
            "clock_getres01",
            "sysconf01",
            "copy_file_range01",
            "chmod01",
            "confstr01",
            "epoll-ltp",
            "posix_fadvise03",
            "posix_fadvise03_64",
            "splice08",
            "signal03",
            "signal05",
            "signal04",
            "fremovexattr02",
            "rename13",
            "utime01",
            "utime02",
            "utime04",
            "accept03",
            "madvise01",
            "fanotify06",
            "llseek03",
            "open_tree02",
            "rename08",
            "rename10",
            "statvfs01",
            "pathconf01",
            "access02",
            "clock_gettime01",
            "fanotify09",
            "clock_nanosleep01",
            "clock_settime02",
            "diotest4",
            "link04",
            "madvise10",
            "utimensat01",
            "clock_gettime02",
            "close_range02",
            "fanotify16",
            "times03",
            "add_key02",
            "arping01.sh",
            "clock_adjtime01",
            "fanotify04",
            // "fpathconf01",
            "fremovexattr01",
            "fspick02",
            "mkdir03",
            "readv01",
            "rename04",
            "rename05",
            "rename06",
            "rename07",
            "statfs01",
            "statfs01_64",
            "access03",
            "access04",
            "add_key01",
            "epoll_ctl02",
            // "fallocate03",
            "fanotify02",
            "fanotify19",
            "fsconfig02",
            "linkat01",
            "bind01",
            "creat06",
            "fcntl36",
            "fcntl36_64",
            "mknod01",
            "setreuid01",
            "splice03",
            "statx01",
            "unlinkat01",
            "utime03",
            "alarm02",
            "capget01",
            "chown05",
            "clock_gettime04",
            // "clone302", // stuck for a while but KILLed
            "dup202",
            "fchmodat01",
            "fcntl02",
            "fcntl02_64",
            "fcntl16",
            "fcntl16_64",
            "fstatat01",
            "lchown01",
            "pipe2_01",
            "posix_fadvise01",
            "posix_fadvise01_64",
            "posix_fadvise02",
            "posix_fadvise02_64",
            // "tgkill03", // stuck for a while but KILLed
            "waitid05",
            "waitid06",
            "accept01",
            "chmod06",
            "clone08",
            "epoll_wait03",
            // "fchmodat02",
            "fcntl05",
            "fcntl05_64",
            // "fcntl15_64", // stuck for a while but KILLed in RvGl
            "fsconfig03",
            "open07",
            "openat01",
            "read02",
            "readlinkat02",
            "renameat01",
            "rmdir02",
            // "setitimer01", // stuck for a while but KILLed
            "socket01",
            "statx02",
            "statx03",
            "stream05",
            "symlink01",
            "symlinkat01",
            "unlink07",
            "waitid01",
            "waitid11",
            "accept4_01",
            "capget02",
            "chown04",
            "chroot03",
            "clock_nanosleep04",
            "clock_settime01",
            "clone301",
            "creat01",
            "dup203",
            "dup204",
            // // "fallocate01",
            // // "fallocate06",
            "fchownat01",
            "fcntl09",
            "fcntl09_64",
            "fcntl10",
            "fcntl10_64",
            "fstat02",
            "fstat02_64",
            "ioctl_ns07",
            "linkat02",
            "lseek01",
            "mknod07",
            "mlock01",
            "munlock01",
            "pwrite02",
            "pwrite02_64",
            "sched_getaffinity01",
            "sched_setscheduler04",
            "shmt03",
            "sigaction01",
            // // "signal01", // stuck for a while but KILLed
            "sigpending02",
            "socket02",
            "timerfd02",
            "waitpid04",
            "waitpid09",
            "writev01",
            "alarm05",
            "atof01",
            "capset01",
            "chdir04",
            "clock_adjtime02",
            "close01",
            // "diotest2",
            // "diotest3",
            // "diotest5",
            // "diotest6",
            // "dup07",
            // "epoll_ctl01",
            // // "faccessat01",
            // "fanotify15",
            // "fork04",
            // "getgroups01",
            // "inode01",
            // "ioctl05",
            // "listen01",
            // "mknodat01",
            // "mmap09",
            // "mremap06",
            // "nanosleep04",
            // "nextafter01",
            // // "pidfd_getfd02", // stuck for a while but KILLed in RvGl
            // "prctl02",
            // "readv02",
            // "sendfile03",
            // "sendfile03_64",
            // "setgroups02",
            // "setresuid04",
            // "setreuid04",
            // "setreuid06",
            // "setreuid07",
            // "shmt02",
            // "sigaction02",
            // "signal02",
            // "socketpair01",
            // "statfs02",
            // "statfs02_64",
            // "syscall01",
            // "ulimit01",
            // "wait401",
            // // "waitid07", // stuck for a while but KILLed
            // // "waitid08", // stuck for a while but KILLed
            // "write05",
            // "abort01",
            // "abs01",
            // "adjtimex01",
            // "alarm03",
            // "alarm06",
            // "alarm07",
            // "bind03",
            // "chown02",
            // "clone01",
            // "connect01",
            // "creat04",
            // "dup01",
            // "dup02",
            // "dup04",
            // "dup207",
            // "dup3_01",
            // "dup3_02",
            // "epoll_create01",
            // "epoll_create1_01",
            // "epoll_create1_02",
            // "epoll_wait06",
            // "epoll_wait07",
            // "eventfd01",
            // "eventfd03",
            // "eventfd05",
            // "eventfd2_01",
            // "eventfd2_03",
            // // "faccessat02",
            // "fanotify08",
            // "fcntl23",
            // "fcntl29",
            // "fcntl29_64",
            // "fork01",
            // "fork10",
            // "fsopen02",
            // "fstat03",
            // "fstat03_64",
            // // "ftest01",
            // // "ftest06",
            // "kill03",
            // "kill11",
            // "link02",
            // "llseek02",
            // "lseek07",
            // "memcmp01",
            // "memcpy01",
            // "mknod02",
            // "mknodat02",
            // "mmap06",
            // "nanosleep02",
            // "pidfd_open02",
            // "pidns05",
            // "pipe04",
            // "poll01",
            // "prctl01",
            // "prctl05",
            // "pread02",
            // "pread02_64",
            // "readlink01",
            // "recv01",
            // "recvfrom01",
            // "removexattr02",
            // "sched_getscheduler01",
            // "send01",
            // "sendto01",
            // "setgid03",
            // "setgroups03",
            // "setpgid01",
            // "setpgrp02",
            // "setrlimit01",
            // "setsockopt01",
            // "settimeofday02",
            // "setuid04",
            // "shmctl02",
            // "shmt05",
            // "shmt07",
            // "sigaltstack02",
            // "signalfd01",
            // "socketpair02",
            // "splice09",
            // "stat02",
            // "stat02_64",
            // "statvfs02",
            // "stream03",
            // "symlink04",
            // "time01",
            // "timerfd_create01",
            // "tkill01",
            // "tkill02",
            // "truncate02",
            // "truncate02_64",
            // "umount2_02",
            // "uname01",
            // "unlink05",
            // "unlink08",
            // "utsname04",
            // "waitid04",
            // "waitpid03",
            // "write02",
            // "write06",
            // "writetest",
            // "writev07",
            // "add_key03",
            // "add_key04",
            // "adjtimex02",
            // "bpf_map01",
            // "bpf_prog01",
            // "bpf_prog02",
            // "bpf_prog05",
            // "brk02",
            // "capset03",
            // "chown01",
            // "chroot02",
            // "clock_nanosleep02",
            // "clone03",
            // "clone05",
            // "clone06",
            // "clone07",
            // "close02",
            // "close_range01",
            // "creat03",
            // "creat05",
            // "cve-2017-17052",
            // "dio_sparse",
            // "diotest1",
            // "dirtyc0w",
            // "dirtypipe",
            // "dup03",
            // "dup06",
            // "dup205",
            // "dup206",
            // "epoll_wait02",
            // "epoll_wait04",
            // "eventfd02",
            // "eventfd2_02",
            // "execve03",
            // "exit01",
            // "exit02",
            // "exit_group01",
            // "fallocate04",
            // "fchdir01",
            // "fchdir02",
            // "fchownat02",
            // "fcntl03",
            // "fcntl03_64",
            // "fcntl04",
            // "fcntl04_64",
            // "fcntl08",
            // "fcntl08_64",
            // "fcntl12",
            // "fcntl12_64",
            // "fcntl34",
            // "fcntl34_64",
            // "fgetxattr03",
            // "fork03",
            // "fork07",
            // "fork08",
            // "fork09",
            // "fork_procs",
            // "ftest03",
            // "ftest04",
            // "ftest05",
            // "ftest07",
            // "ftest08",
            // "get_robust_list01",
            // "getrusage04",
            // "growfiles",
            // "kill06",
            // "kill08",
            // "kill09",
            // "kill12",
            // "lchown03",
            // "lftest",
            // "link05",
            // "link08",
            // "llseek01",
            // "madvise05",
            // "memfd_create02",
            // "memset01",
            // "mkdir05",
            // "mknod09",
            // "mlock03",
            // "mlock04",
            // "mmap01",
            // "mmap05",
            // "mmap08",
            // "mmap1", //normally time consuming
            // "mmap11",
            // "mmap18",
            // "mmap19",
            // "mmapstress01",
            // "mmapstress04",
            // "mprotect03",
            // "mprotect04",
            // "mprotect05",
            // "msync01",
            // "msync02",
            // "munmap01",
            // "munmap02",
            // "nanosleep01",
            // "newuname01",
            // "nfs05_make_tree",
            // "nptl01",
            // "open01",
            // "open02",
            // "open03",
            // "open04",
            // "open09",
            // "openat02",
            // "page01",
            // "pathconf02",
            // "pidns32",
            // "pipe01",
            // "pipe05",
            // "pipe06",
            // "pipe07",
            // "pipe09",
            // "pipe10",
            // "pipe12",
            // "pipe14",
            // "pread01",
            // "pread01_64",
            // "pselect01",
            // "pselect01_64",
            // "pselect03",
            // "pselect03_64",
            // "pth_str01",
            // "pth_str02",
            // "pth_str03",
            // "pwrite01",
            // "pwrite01_64",
            // "pwrite03",
            // "pwrite03_64",
            // "pwrite04",
            // "pwrite04_64",
            // "read01",
            // "read04",
            // "readdir01",
            // "removexattr01",
            // "rename14",
            // "renameat201",
            // "rmdir01",
            // "rt_sigprocmask01",
            // "sbrk01",
            // "sbrk02",
            // "sched_setaffinity01",
            // "sched_yield01",
            // "select02",
            // "sendfile06",
            // "sendfile06_64",
            // "sendfile08",
            // "sendfile08_64",
            // "sendto02",
            // "set_robust_list01",
            // "set_tid_address01",
            // "setegid02",
            // "setgid01",
            // "setgid02",
            // "setgroups01",
            // "setgroups04",
            // "setitimer02",
            // "setpgrp01",
            // "setresuid05",
            // "setrlimit02",
            // "setrlimit04",
            // "setrlimit05",
            // "setsid01",
            // "setsockopt03",
            // "setsockopt04",
            // "settimeofday01",
            // "setuid01",
            // "setuid03",
            // "shmctl06",
            // "shmem_2nstest", //Stuck for a while, killed
            // "shmnstest",
            // "sigaltstack01",
            // "sigprocmask01",
            // "splice01",
            // "splice02",
            // "stack_space",
            // "stime01",
            // "stream01",
            // "stream04",
            // "string01",
            // "symlink02",
            // "sysinfo01",
            // "sysinfo02",
            // "tgkill01",
            // "times01",
            // "umount01",
            // "uname02",
            // "uname04",
            // "utime07",
            // "utsname01",
            // "wait01",
            // "wait02",
            // "wait402",
            // "wait403",
            // "waitid02",
            // "waitid03",
            // "waitid09",
            // "waitid10",
            // "waitpid06",
            // "waitpid07",
            // "waitpid08",
            // "write01",
            // "write03",
            // "writev02",
            // "writev05",
            // "writev06",
        ]);

        println!("#### OS COMP TEST GROUP START ltp-musl ####");
        for test in LATESTCASES {
            println!("RUN LTP CASE {}", test);
            let cmd = format!("ltp/testcases/bin/{}", test);
            run_cmd(&cmd);
            println!("FAIL LTP CASE {} : 0", test);
        }
        println!("#### OS COMP TEST GROUP END ltp-musl ####");
    }

    pub fn runltp_lagl() {
        let LATESTCASES = Vec::from([
            "fanotify01",
            "splice07",
            "fanotify14",
            "epoll_ctl03",
            "access01",
            "rt_sigaction01",
            "rt_sigaction02",
            "rt_sigaction03",
            "chdir01",
            "waitpid01",
            "fsetxattr01",
            "setxattr01",
            "rename01",
            "rename03",
            "pipe11",
            "mkdir09",
            "memfd_create01", // stuck for a while but KILLed
            "fgetxattr01",
            "clock_getres01",
            "sysconf01",
            "copy_file_range01",
            "chmod01",
            "confstr01",
            "epoll-ltp",
            "posix_fadvise03",
            "posix_fadvise03_64",
            "splice08",
            "signal03",
            "signal05",
            "signal04",
            "fremovexattr02",
            "rename13",
            "utime01",
            "utime02",
            "utime04",
            "accept03",
            "madvise01",
            "fanotify06",
            "llseek03",
            "open_tree02",
            "rename08",
            "rename10",
            "statvfs01",
            "pathconf01",
            "access02",
            "clock_gettime01",
            "fanotify09",
            "clock_nanosleep01",
            "clock_settime02",
            "diotest4",
            "link04",
            "madvise10",
            "utimensat01",
            "clock_gettime02",
            "close_range02",
            "fanotify16",
            "times03",
            "add_key02",
            "arping01.sh",
            "clock_adjtime01",
            "fanotify04",
            // "fpathconf01",
            "fremovexattr01",
            "fspick02",
            "mkdir03",
            "readv01",
            "rename04",
            "rename05",
            "rename06",
            "rename07",
            "statfs01",
            "statfs01_64",
            "access03",
            "access04",
            "add_key01",
            "epoll_ctl02",
            "fallocate03",
            "fanotify02",
            "fanotify19",
            "fsconfig02",
            "linkat01",
            "bind01",
            "creat06",
            "fcntl36",
            "fcntl36_64",
            "mknod01",
            "setreuid01",
            "splice03",
            "statx01",
            "unlinkat01",
            "utime03",
            "alarm02",
            "capget01",
            "chown05",
            "clock_gettime04",
            // "clone302", // stuck for a while but KILLed
            "dup202",
            "fchmodat01",
            "fcntl02",
            "fcntl02_64",
            "fcntl16",
            "fcntl16_64",
            "fstatat01",
            "lchown01",
            "pipe2_01",
            "posix_fadvise01",
            "posix_fadvise01_64",
            "posix_fadvise02",
            "posix_fadvise02_64",
            // "tgkill03", // stuck for a while but KILLed
            "waitid05",
            "waitid06",
            "accept01",
            "chmod06",
            "clone08",
            "epoll_wait03",
            // "fchmodat02",
            "fcntl05",
            "fcntl05_64",
            // "fcntl15_64", // stuck for a while but KILLed in RvGl
            "fsconfig03",
            "open07",
            "openat01",
            "read02",
            "readlinkat02",
            "renameat01",
            "rmdir02",
            // "setitimer01", // stuck for a while but KILLed
            "socket01",
            "statx02",
            "statx03",
            "stream05",
            "symlink01",
            "symlinkat01",
            "unlink07",
            "waitid01",
            "waitid11",
            "accept4_01",
            "capget02",
            "chown04",
            "chroot03",
            "clock_nanosleep04",
            "clock_settime01",
            "clone301",
            "creat01",
            "dup203",
            "dup204",
            // "fallocate01",
            // "fallocate06",
            "fchownat01",
            "fcntl09",
            "fcntl09_64",
            "fcntl10",
            "fcntl10_64",
            "fstat02",
            "fstat02_64",
            "ioctl_ns07",
            "linkat02",
            "lseek01",
            "mknod07",
            "mlock01",
            "munlock01",
            "pwrite02",
            "pwrite02_64",
            "sched_getaffinity01",
            "sched_setscheduler04",
            "shmt03",
            "sigaction01",
            // "signal01", // stuck for a while but KILLed
            "sigpending02",
            "socket02",
            "timerfd02",
            "waitpid04",
            "waitpid09",
            "writev01",
            "alarm05",
            "atof01",
            "capset01",
            "chdir04",
            "clock_adjtime02",
            "close01",
            // "diotest2",
            // "diotest3",
            // "diotest5",
            // "diotest6",
            // "dup07",
            // "epoll_ctl01",
            // // "faccessat01",
            // "fanotify15",
            // "fork04",
            // "getgroups01",
            // "inode01",
            // "ioctl05",
            // "listen01",
            // "mknodat01",
            // "mmap09",
            // "mremap06",
            // "nanosleep04",
            // "nextafter01",
            // // "pidfd_getfd02", // stuck for a while but KILLed in RvGl
            // "prctl02",
            // "readv02",
            // "sendfile03",
            // "sendfile03_64",
            // "setgroups02",
            // "setresuid04",
            // "setreuid04",
            // "setreuid06",
            // "setreuid07",
            // "shmt02",
            // "sigaction02",
            // "signal02",
            // "socketpair01",
            // "statfs02",
            // "statfs02_64",
            // "syscall01",
            // "ulimit01",
            // "wait401",
            // // "waitid07", // stuck for a while but KILLed
            // // "waitid08", // stuck for a while but KILLed
            // "write05",
            // "abort01",
            // "abs01",
            // "adjtimex01",
            // "alarm03",
            // "alarm06",
            // "alarm07",
            // "bind03",
            // "chown02",
            // "clone01",
            // "connect01",
            // "creat04",
            // "dup01",
            // "dup02",
            // "dup04",
            // "dup207",
            // "dup3_01",
            // "dup3_02",
            // "epoll_create01",
            // "epoll_create1_01",
            // "epoll_create1_02",
            // "epoll_wait06",
            // "epoll_wait07",
            // "eventfd01",
            // "eventfd03",
            // "eventfd05",
            // "eventfd2_01",
            // "eventfd2_03",
            // // "faccessat02",
            // "fanotify08",
            // "fcntl23",
            // "fcntl29",
            // "fcntl29_64",
            // "fork01",
            // "fork10",
            // "fsopen02",
            // "fstat03",
            // "fstat03_64",
            // // "ftest01",
            // // "ftest06",
            // "kill03",
            // "kill11",
            // "link02",
            // "llseek02",
            // "lseek07",
            // "memcmp01",
            // "memcpy01",
            // "mknod02",
            // "mknodat02",
            // "mmap06",
            // "nanosleep02",
            // "pidfd_open02",
            // "pidns05",
            // "pipe04",
            // "poll01",
            // "prctl01",
            // "prctl05",
            // "pread02",
            // "pread02_64",
            // "readlink01",
            // "recv01",
            // "recvfrom01",
            // "removexattr02",
            // "sched_getscheduler01",
            // "send01",
            // "sendto01",
            // "setgid03",
            // "setgroups03",
            // "setpgid01",
            // "setpgrp02",
            // "setrlimit01",
            // "setsockopt01",
            // "settimeofday02",
            // "setuid04",
            // "shmctl02",
            // "shmt05",
            // "shmt07",
            // "sigaltstack02",
            // "signalfd01",
            // "socketpair02",
            // "splice09",
            // "stat02",
            // "stat02_64",
            // "statvfs02",
            // "stream03",
            // "symlink04",
            // "time01",
            // "timerfd_create01",
            // "tkill01",
            // "tkill02",
            // "truncate02",
            // "truncate02_64",
            // "umount2_02",
            // "uname01",
            // "unlink05",
            // "unlink08",
            // "utsname04",
            // "waitid04",
            // "waitpid03",
            // "write02",
            // "write06",
            // "writetest",
            // "writev07",
            // "add_key03",
            // "add_key04",
            // "adjtimex02",
            // "bpf_map01",
            // "bpf_prog01",
            // "bpf_prog02",
            // "bpf_prog05",
            // "brk02",
            // "capset03",
            // "chown01",
            // "chroot02",
            // "clock_nanosleep02",
            // "clone03",
            // "clone05",
            // "clone06",
            // "clone07",
            // "close02",
            // "close_range01",
            // "creat03",
            // "creat05",
            // "cve-2017-17052",
            // "dio_sparse",
            // "diotest1",
            // "dirtyc0w",
            // "dirtypipe",
            // "dup03",
            // "dup06",
            // "dup205",
            // "dup206",
            // "epoll_wait02",
            // "epoll_wait04",
            // "eventfd02",
            // "eventfd2_02",
            // "execve03",
            // "exit01",
            // "exit02",
            // "exit_group01",
            // "fallocate04",
            // "fchdir01",
            // "fchdir02",
            // "fchownat02",
            // "fcntl03",
            // "fcntl03_64",
            // "fcntl04",
            // "fcntl04_64",
            // "fcntl08",
            // "fcntl08_64",
            // "fcntl12",
            // "fcntl12_64",
            // "fcntl34",
            // "fcntl34_64",
            // "fgetxattr03",
            // "fork03",
            // "fork07",
            // "fork08",
            // "fork09",
            // "fork_procs",
            // "ftest03",
            // "ftest04",
            // "ftest05",
            // "ftest07",
            // "ftest08",
            // "get_robust_list01",
            // "getrusage04",
            // "growfiles",
            // "kill06",
            // "kill08",
            // "kill09",
            // "kill12",
            // "lchown03",
            // "lftest",
            // "link05",
            // "link08",
            // "llseek01",
            // "madvise05",
            // "memfd_create02",
            // "memset01",
            // "mkdir05",
            // "mknod09",
            // "mlock03",
            // "mlock04",
            // "mmap01",
            // "mmap05",
            // "mmap08",
            // // "mmap1", //normally time consuming
            // "mmap11",
            // "mmap18",
            // "mmap19",
            // "mmapstress01",
            // "mmapstress04",
            // "mprotect03",
            // "mprotect04",
            // "mprotect05",
            // "msync01",
            // "msync02",
            // "munmap01",
            // "munmap02",
            // "nanosleep01",
            // "newuname01",
            // "nfs05_make_tree",
            // "nptl01",
            // "open01",
            // "open02",
            // "open03",
            // "open04",
            // "open09",
            // "openat02",
            // "page01",
            // "pathconf02",
            // "pidns32",
            // "pipe01",
            // "pipe05",
            // "pipe06",
            // "pipe07",
            // "pipe09",
            // "pipe10",
            // "pipe12",
            // "pipe14",
            // "pread01",
            // "pread01_64",
            // "pselect01",
            // "pselect01_64",
            // "pselect03",
            // "pselect03_64",
            // "pth_str01",
            // "pth_str02",
            // "pth_str03",
            // "pwrite01",
            // "pwrite01_64",
            // "pwrite03",
            // "pwrite03_64",
            // "pwrite04",
            // "pwrite04_64",
            // "read01",
            // "read04",
            // "readdir01",
            // "removexattr01",
            // "rename14",
            // "renameat201",
            // "rmdir01",
            // "rt_sigprocmask01",
            // "sbrk01",
            // "sbrk02",
            // "sched_setaffinity01",
            // "sched_yield01",
            // "select02",
            // "sendfile06",
            // "sendfile06_64",
            // "sendfile08",
            // "sendfile08_64",
            // "sendto02",
            // "set_robust_list01",
            // "set_tid_address01",
            // "setegid02",
            // "setgid01",
            // "setgid02",
            // "setgroups01",
            // "setgroups04",
            // "setitimer02",
            // "setpgrp01",
            // "setresuid05",
            // "setrlimit02",
            // "setrlimit04",
            // "setrlimit05",
            // "setsid01",
            // "setsockopt03",
            // "setsockopt04",
            // "settimeofday01",
            // "setuid01",
            // "setuid03",
            // "shmctl06",
            // // "shmem_2nstest", //Stuck for a while, killed
            // "shmnstest",
            // "sigaltstack01",
            // "sigprocmask01",
            // "splice01",
            // "splice02",
            // "stack_space",
            // "stime01",
            // "stream01",
            // "stream04",
            // "string01",
            // "symlink02",
            // "sysinfo01",
            // "sysinfo02",
            // "tgkill01",
            // "times01",
            // "umount01",
            // "uname02",
            // "uname04",
            // "utime07",
            // "utsname01",
            // "wait01",
            // "wait02",
            // "wait402",
            // "wait403",
            // "waitid02",
            // "waitid03",
            // "waitid09",
            // "waitid10",
            // "waitpid06",
            // "waitpid07",
            // "waitpid08",
            // "write01",
            // "write03",
            // "writev02",
            // "writev05",
            // "writev06",
        ]);

        println!("#### OS COMP TEST GROUP START ltp-glibc ####");
        for test in LATESTCASES {
            println!("RUN LTP CASE {}", test);
            let cmd = format!("ltp/testcases/bin/{}", test);
            run_cmd(&cmd);
            println!("FAIL LTP CASE {} : 0", test);
        }
        println!("#### OS COMP TEST GROUP END ltp-glibc ####");
    }
}

// "pidfd_send_signal01",
// "pidfd_send_signal02",
// "pidfd_send_signal03",
// "rt_sigprocmask01",
// "rt_sigprocmask02",
// "rt_sigqueueinfo01",
// "rt_sigsuspend01",
// "sigaction01",
// "sigaction02",
// "sigaltstack01",
// "sigaltstack02",
// "sighold02",
// "signal01",
// "signal02",
// "signal03",
// "signal04",
// "signal05",
// "signal06",
// "signalfd01",
// "signalfd4_01",
// "signalfd4_02",
// "sigpending02",
// "sigprocmask01",
// "sigrelse01",
// "sigsuspend01",
// "sigtimedwait01",
// "sigwait01",
// "sigwaitinfo01",

// "pidfd_send_signal01", stuck and ESRCH
// "pidfd_send_signal02", enoent broken
// "pidfd_send_signal03", skiped for file not found
// "rt_sigprocmask01", *pass
// "rt_sigprocmask02", pass
// "rt_sigqueueinfo01", 138 unimplemented
// "rt_sigsuspend01", nothing
// "sigaction01", pass
// "sigaction02", pass
// "sigaltstack01", pass
// "sigaltstack02", pass
// "sighold02", “signal handler was executed”
// "signal01", timeout
// "signal02", pass
// "signal03", pass
// "signal04", pass
// "signal05", pass
// "signal06", not on x86
// "signalfd01", pass
// "signalfd4_01", "signalfd4(SFD_CLOEXEC) does not set close-on-exec flag"
// "signalfd4_02", "signalfd4(SFD_CLOEXEC) does not set close-on-exec flag"
// "sigpending02", *4 pass
// "sigprocmask01", *pass
// "sigrelse01", failed
// "sigsuspend01", nothing
// "sigtimedwait01", timeout
// "sigwait01", timeout
// "sigwaitinfo01", timeout

pub fn run_ltp(cmd: &str, test: &str) {
    if fork() == 0 {
        let r = crate::execve("./busybox", &["./busybox", "sh", "-c", cmd], &[]);
    } else {
        let mut result: i32 = 0;
        crate::waitpid(-1, &mut result, 0);
    }
}
